builds:
  - ldflags:
      - -s -w -X github.com/k-kinzal/pr/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE

dockers:
  - image_templates:
      - docker.io/kinzal/{{ .ProjectName }}:latest-amd64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Version }}-amd64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}-amd64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - docker.io/kinzal/{{ .ProjectName }}:latest-arm64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Version }}-arm64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}-arm64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: docker.io/kinzal/{{ .ProjectName }}:latest
    image_templates:
      - docker.io/kinzal/{{ .ProjectName }}:latest-amd64
      - docker.io/kinzal/{{ .ProjectName }}:latest-arm64
  - name_template: docker.io/kinzal/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Version }}-amd64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}
    image_templates:
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}-amd64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}-arm64
  - name_template: docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
    image_templates:
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64
      - docker.io/kinzal/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64
